name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: actions/setup-node@v3

      - name: Build Docker image
        run: |
          docker build -t next-app-img .

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "."  # Lokasi file Docker image lokal
          target: "/home/ec2-user"  # Lokasi tujuan di EC2

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop next-app-container || true
            docker rm next-app-container || true
            docker load -i /home/ec2-user/next-app-img.tar
            docker run -d -p 3000:3000 --name next-app-container next-app-img
