name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: actions/setup-node@v3

      - name: Build Docker image
        run: |
          docker build -t next-app-img .

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "next-app-img.tar"  # Update with the correct file name if needed
          target: "/home/ec2-user/github"  # Lokasi tujuan di EC2

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            CONTAINER_NAME=next-app-container
            if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
                echo "Stopping and removing existing container: ${CONTAINER_NAME}"
                docker stop ${CONTAINER_NAME}
                docker rm ${CONTAINER_NAME}
            else
                echo "Container '${CONTAINER_NAME}' not found."
            fi
            docker load -i /home/ec2-user/github/next-app-img.tar
            docker run -d -p 3000:3000 --name ${CONTAINER_NAME} next-app-img
